nguage: python
python:
  - "2.7"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers 
  - pip install numpy
  - pip install pyopencl
script:
  - nosetests
